name: ysp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  flutter_tilt: ^3.0.0
  go_router: ^13.2.2
  icons_plus: ^5.0.0
  toastification: ^1.2.1
  date_format: ^2.0.7
  lottie: ^3.1.0
  url_launcher: ^6.2.5
  google_fonts: ^6.2.1
  animated_line_through: ^1.0.4
  animated_flip_counter: ^0.3.4
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lotties/
